image: node:10.13.0-alpine

stages:
  - build
  - publish

cache:
  key: $CI_COMMIT_REF_NAME
  paths:
    - node_modules/
  untracked: false

before_script:
  - apk add jq
  - npm i
  - jq -r '.peerDependencies | to_entries[] | .key + "@" + .value' package.json | xargs npm i --no-save

build-development:
  stage: build
  script:
    - npx gulp compile

build-bundle:
  stage: build
  script:
    - npx gulp compile:bundle

publish:
  before_script:
    - 'echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc'
  stage: publish
  script:
    - npm publish
  only:
    refs:
      - tags
